name: queenbee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  bloc_test: ^9.1.3
  cached_network_image: ^3.4.1
  dio: ^5.1.2
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  material_color_utilities: ^0.11.1
  shared_preferences: ^2.1.2
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
